
#' Download and read odds in xml format from bookmaker.eu into R
#'
#' @param url domain or path of the xml file
#'
#' @return `xml_document`
#' @export
#'
#' @examples
#' odds <- bm_get_odds_xml()
#'
#' @importFrom xml2 read_xml
bm_get_odds_xml <- function(url="http://lines.bookmaker.eu") {
  try(xml2::read_xml(url))
}

#' Helper function to get unique `IdSport` for filter xml. Takes xml obj and returns all available sports
#'
#' @param odds xml object from bookmaker.eu
#'
#' @return A character vector with unique values
#' @noRd
#'
#' @examples
#' /dontrun{
#' ids <- bm_get_sport_ids(odds)}
#'
#' @importFrom xml2 xml_find_all xml_attr
#'
bm_get_sport_ids <- function(odds) {
  odds %>%
    xml2::xml_find_all('/Data/Leagues/league') %>%
    xml2::xml_attr('IdSport') %>%
    unique()
}

#' Helper function to get unique `Description` for filter xml
#'
#' @param odds xml object from bookmaker.eu
#'
#' @return A character vector with unique values
#' @noRd
#'
#' @examples
#' /dontrun{
#' ids <- bm_get_desc(odds)}
#'
#' @importFrom xml2 xml_attr
bm_get_desc <- function(odds) {
  odds %>%
    xml2::xml_attr('Description') %>%
    unique() %>%
    sort()
}

#' Helper function return either match-ups or futures.
#'
#' @param odds A xml document of bookmaker's odds
#' @param type The odds type to return. Either match-ups or futures.
#'
#' @return A xml_document filtered for either match-ups or futures.
#' @noRd
#'
#' @examples
#' /dontrun{
#' bm_filter_by_btype(odds, 'futures')
#' }
#'
#' @importFrom xml2 xml_find_all xml_find_first xml_has_attr
#' @importFrom purrr discard keep
#'
bm_filter_by_btype <- function(odds,type='matchups'){
  bm_lines <- xml2::xml_find_all(odds, '/Data/Leagues/league')
  type <- match.arg(type, c('matchups','futures'))
  fn <- ifelse(type == 'matchups', purrr::discard, purrr::keep)
  fn(bm_lines,function(lines){
    xml2::xml_find_first(lines,'game/line') %>% xml2::xml_has_attr('tmnum')}
  )
}

#' Helper function to filter xml by `Description`. Use one of the ids generated by `bm_get_desc`
#'
#' @param odds xml_object of league events
#' @param sport A description of the events
#'
#' @return xml_object filtered for specific descriptions
#' @noRd
#'
#' @examples
#' /dontrun{
#' bm_filter_by_btype(odds,'matchups') %>%
#' bm_filter_on_desc('NBA')
#' }
#'
#' @importFrom xml2 xml_find_all xml_attr
#' @importFrom purrr keep
#'
bm_filter_on_desc <- function(odds, description) {
  odds %>%
    xml2::xml_find_all('/Data/Leagues/league') %>%
    purrr::keep(function(lines){
      xml2::xml_attr(lines,'Description') == description})
}

#' Get game details from `xml_object`. Pull out main game detail columns.
#'
#' @param odds A xml object
#'
#' @return A dataframe of game details
#' @noRd
#'
#' @examples
#' /dontrun{
#' mk_matchup_df(odds)
#' }
#'
#' @importFrom xml2 xml_find_all xml_attr
#' @importFrom dplyr tibble
#' @importFrom lubridate ymd
#' @importFrom hms as_hms
#'
bm_matchup_details <- function(odds) {
  games <- xml2::xml_find_all(odds, 'game')
  dplyr::tibble(
    id_sprt = games %>% xml2::xml_attr('idspt'),
    id_lg = games %>% xml2::xml_attr('idlg'),
    period = games %>% xml2::xml_attr('gpd'),
    desc = games %>% xml2::xml_attr('gdesc'),
    v = games %>% xml2::xml_attr('vtm'),
    h = games %>% xml2::xml_attr('htm'),
    v_num = games %>% xml2::xml_attr('vnum'),
    h_num = games %>% xml2::xml_attr('hnum'),
    dt = games %>% xml2::xml_attr('gmdt') %>% lubridate::ymd(),
    tm = games %>% xml2::xml_attr('gmtm') %>% hms::as_hms()
  )
}

#' Extract game odds for each match-up
#'
#' @param odds A xml object
#'
#' @return A dataframe with game match-up odds
#' @noRd
#'
#' @examples
#' /dontrun {
#' mk_matchup_lines(odds)
#' }
#'
#' @importFrom xml2 xml_find_all xml_attr
#' @importFrom dplyr tibble mutate_all
#'
bm_matchup_lines <- function(odds) {
  lines <- odds %>% xml2::xml_find_all('game/line')
  dplyr::tibble(
    h_ml = lines %>% xml2::xml_attr('hoddst'),
    p_ml = lines %>% xml2::xml_attr('vsph'),
    v_ml = lines %>% xml2::xml_attr('voddst'),
    h_sprd = lines %>% xml2::xml_attr('hsprdt'),
    h_odd = lines %>% xml2::xml_attr('hsprdoddst'),
    v_sprd = lines %>% xml2::xml_attr('vsprdt'),
    v_odd = lines %>% xml2::xml_attr('vsprdoddst'),
    ou = lines %>% xml2::xml_attr('unt'),
    o = lines %>% xml2::xml_attr('ovoddst'),
    u = lines %>% xml2::xml_attr('unoddst')
  ) %>%
    dplyr::mutate_all(as.numeric)
}

#' Get details for futures.
#'
#' @param odds An xml object
#'
#' @return A dataframe with details for event betting event
#' @noRd
#'
#' @importFrom xml2 xml_find_all xml_attr
#' @importFrom dplyr tibble
#' @importFrom lubridate ymd
#' @importFrom hms as_hms
#'
bm_get_future_details <- function(odds){
  games <- xml2::xml_find_all(odds, 'game')
  dplyr::tibble(
    prop = games %>% xml2::xml_attr('htm'),
    id_sprt = games %>% xml2::xml_attr('idspt'),
    id_lg = games %>% xml2::xml_attr('idlg'),
    dt = games %>% xml2::xml_attr('gmdt') %>% lubridate::ymd(),
    tm = games %>% xml2::xml_attr('gmtm') %>% hms::as_hms(),
    b_id = 1:length(games) %>% as.character()
  )
}

#' Get odds and selection names for futures
#'
#' @param odds An xml object
#'
#' @return A dataframe with futures odds for betting event
#' @noRd
#'
#' @importFrom xml2 xml_attr
#' @importFrom dplyr tibble mutate_at vars one_of
#'
bm_get_future_lines <- function(odds) {
  dplyr::tibble(
    rot = odds %>% xml2::xml_attr('tmnum'),
    selection = odds %>% xml2::xml_attr('tmname'),
    odds = odds %>% xml2::xml_attr('odds')
  ) %>%
    dplyr::mutate_at(dplyr::vars(dplyr::one_of(c('rot','odds'))),
                     as.numeric)
}

#' Helper function to combine details and odds for match-ups
#'
#' @param odds An xml_object
#'
#' @return A dataframe with all data for match-ups including odds
#' @noRd
#'
#' @importFrom dplyr bind_cols
#'
bm_matchup_pipeline <- function(odds){
  gm_details <- bm_matchup_details(odds)
  gm_odds <- bm_matchup_lines(odds)
  dplyr::bind_cols(gm_details, gm_odds)
}

#' Helper function to combine details and odds for futures
#'
#' @param odds An xml_object
#'
#' @return A dataframe with all data for future events
#' @noRd
#'
#' @importFrom xml2 xml_find_all
#' @importFrom dplyr bind_rows left_join select contains
#' @importFrom purrr map
#'
bm_futures_pipeline <- function(odds){
  gm_details <- bm_get_future_details(odds)
  gm_odds <- xml2::xml_find_all(odds, 'game') %>%
    purrr::map(function(game){
      xml2::xml_find_all(game,'line')}) %>%
    purrr::map(bm_get_future_lines) %>%
    dplyr::bind_rows(.id = 'b_id')
  dplyr::left_join(gm_details, gm_odds, by=c('b_id')) %>%
    dplyr::select(!dplyr::contains(c('b_id')))
}

#' Determine if a line is is future or a match-up
#'
#' @param odds xml_object
#'
#' @return A logical
#' @noRd
#'
#' @importFrom xml2 xml_find_first xml_has_attr
#' @importFrom purrr pluck
#'
is_future <- function(odds) {
  xml2::xml_find_first(odds, 'game/line') %>%
    xml2::xml_has_attr('tmname') %>%
    purrr::pluck(1)
}

#' Convert odds xml to a dataframe via one of the two pipelines (match-ups and futures)
#'
#' @param odds xml_object
#'
#' @return A dataframe
#' @noRd
#'
bm_convert_to_df <- function(odds) {
  if (is_future(odds)) {
    return(bm_futures_pipeline(odds))
  } else {
    return(bm_matchup_pipeline(odds))
  }
}
